### PR TITLE
fix: NO_RESULT_CALLBACK_FOUND in neovim

### LINKED ISSUE #9: NeoVim LSP Setup / Config NO_RESULT_CALLBACK_FOUND ...
### Describe the bug

When using this config in NeoVim: 

```lua
local configs = require('lspconfig.configs')
local lspconfig = require('lspconfig')
if not configs['v-analyzer'] then
  configs['v-analyzer'] = {
    default_config = {
      cmd = { 'v-analyzer' },
      root_dir = lspconfig.util.root_pattern('.git', '.v-analyzer'),
      filetypes = { 'v', 'vlang' },
    },
  }
end
lspconfig['v-analyzer'].setup {}
```

I am getting this error when editing `.v` files

```
LSP[v-analyzer]: Error NO_RESULT_CALLBACK_FOUND: {
  id = 3,
  jsonrpc = "2.0"
}
```

How are y'all setting up `v-analyzer` in NeoVim/LunarVim?

### Expected Behavior

LSP to work

### Current Behavior

LSP doesn't work as per error message above

### Reproduction Steps

1) Paste config into config.lua or equivalent

2) Open `hello.v` and witness errors upon LSP attachment

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Environment details (`v doctor` output)

`$ v doctor`

```
V full version: V 0.4.0 ab258ae
OS: linux, Ubuntu 22.04.1 LTS (WSL 2) (chroot)
Processor: 6 cpus, 64bit, little endian, Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

getwd: /home/jstitt/playground/vlang
vexe: /home/jstitt/repos/v/v
vexe mtime: 2023-07-03 20:09:28

vroot: OK, value: /home/jstitt/repos/v
VMODULES: OK, value: /home/jstitt/.vmodules
VTMP: OK, value: /tmp/v_1000

Git version: git version 2.34.1
Git vroot status: weekly.2023.27-1-gab258aeb (3 commit(s) behind V master)
.git/config present: true

CC version: cc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3
```

### Editor name

NeoVim

### v-analyzer Version

v-analyzer version 0.0.1-beta.1

### VS Code Extension Version

N/A

### PR DESCRIPTION
**Pull request by demizer**
The spec says "Every processed request must send a response back to the sender of the request." The Signature Help response was returning null (which the spec also says is okay, but neovim does not accept this).

So return an empty struct instead.

closes #9

NOTE: this PR is only tested in Neovim

### CODE REVIEW

**Review by ttytm — COMMENTED** [review]
Good work, this fixes it for me for a good part.

I have two points
1. There are more occurrences in the function that would return none and cause the error.
 
   To fix this and to get compiler assistance with it, the return type could be updated to not return an option. E.g.
   
   https://github.com/ttytm/v-analyzer/commit/210265639d58a8d97a52f9c9029fc3ce2878eadd

2. The error can still happen for other server features. E.g. in `features_definition.v` when trying to go to a definition. Here, a similar update like you did and like the suggestions above mention could be made.

**Comment by demizer** [comment]
Thanks @ttytm, will update later tonight.

**Review by ttytm — APPROVED** [review]
LGTM :+1:

I think it's an adequate solution. Though I'm not too familiar with the v-analyzer code base yet. When a free moments open up, we can also check how more matures projects like e.g. rust analyzer are handling those cases, and maybe refine further :slightly_smiling_face:.

**Comment by spytheman** [comment]
It looks good to me too. We can always improve it later.

**Pull request merged**
